name: Scala CI

on:
 schedule:
    - cron: '0 0 1 * *'

  # Provide support for manually triggering the workflow via GitHub.  
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: ['zulu', 'temurin']
        java: ['17', '11']
    name: Java ${{ matrix.Java }} (${{ matrix.distribution }})    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17[zulu]
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: sbt
          # cache-dependency-path: | # optional
          #    ./build.sbt
          #    ./project/build.properties
      - name: Build project
        run: sbt compile 

      